### PR TITLE
Improve first-time launch instructions

### PR DESCRIPTION
**Pull request by vadi2**
I'm pretty new to the .NET ecosystem and the getting started instructions weren't working out - hopefully this is the right way to go about creating a new Qml.Net project.

### CODE REVIEW

**Comment by pauldotknopf** [comment]
Thanks for the PR.

Yeah, there are some assumptions made about your level of experience with .NET/.NET Core. With that said, I'd prefer to keep the minusha of .NET out of the Qml.Net docs. Otherwise, where do you end ;)

**Comment by pauldotknopf** [comment]
By the way, you have to ```cd console``` after creating the console project.

**Comment by vadi2** [comment]
That is true, but just having the steps for a simple 'hello world' would go a long way!

**Comment by vadi2** [comment]
Thanks! Is there a chatroom for this project? I would rather not spam the PR and I didn't find anything on gitter.im.

**Comment by pauldotknopf** [comment]
https://gitter.im/qmlnet/Lobby

**Pull request closed without merging**
