### PR TITLE
Support QResource.UnregisterResource.

### PR DESCRIPTION
**Pull request by MaxMommersteeg**

### CODE REVIEW

**Comment by pauldotknopf** [comment]
Ignore the failing build. The AppVeyor env has a newer Qt.

**Comment by MaxMommersteeg** [comment]
Should we upgrade to this newer version of Qt? Or modify `appveyor.bat`?

**Comment by pauldotknopf** [comment]
Update Qt to the latest release. I'm not sure where it is at right now, are what exact version in on AppVeyor.

I also don't like the idea of builds "just breaking" over time. I'd like to look into a way to automatically install a very specific version of Qt on the Windows environment.

**Comment by MaxMommersteeg** [comment]
Indeed, current manner seems a bit brittle.

**Pull request merged**
